const ADD_EMPLOYEE = 'app/users/ADD_EMPLOYEE';
const ADD_EMPLOYEE_SUCCESS = 'app/users/ADD_EMPLOYEE_SUCCESS';
const ADD_EMPLOYEE_FAILURE = 'app/users/ADD_EMPLOYEE_FAILURE';

const GET_EMPLOYEES = 'app/users/GET_EMPLOYEES';
const GET_EMPLOYEES_SUCCESS = 'app/users/GET_EMPLOYEES_SUCCESS';
const GET_EMPLOYEES_FAILURE = 'app/users/GET_EMPLOYEES_FAILURE';

export default {
  ADD_EMPLOYEE,
  ADD_EMPLOYEE_SUCCESS,
  ADD_EMPLOYEE_FAILURE,
  GET_EMPLOYEES,
  GET_EMPLOYEES_SUCCESS,
  GET_EMPLOYEES_FAILURE
};
